# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec for Funmite POS v1.2.0

import sys
from pathlib import Path

block_cipher = None
src_root = Path(SPECPATH)

a = Analysis(
    [str(src_root / "run.py")],
    pathex=[str(src_root)],
    binaries=[],
    datas=[
        (str(src_root / "app" / "data" / "migrations"), "app/data/migrations"),
        (str(src_root / "app" / "assets"), "app/assets"),
    ],
    hiddenimports=[
        "app",
        "app.config",
        "app.main",
        "app.logging_config",
        "app.data.db",
        "app.data.models",
        "app.data.seed",
        "app.data.migrations",
        "app.data.migrations.runner",
        "app.data.migrations.versions",
        "app.data.migrations.versions.001_initial",
        "app.data.migrations.versions.002_audit_logs",
        "app.data.migrations.versions.003_sync_metadata",
        "app.data.repositories",
        "app.data.repositories.base",
        "app.data.repositories.user_repository",
        "app.data.repositories.category_repository",
        "app.data.repositories.product_repository",
        "app.data.repositories.customer_repository",
        "app.data.repositories.sale_repository",
        "app.data.repositories.inventory_repository",
        "app.data.repositories.exchange_repository",
        "app.data.repositories.supplier_repository",
        "app.data.repositories.purchase_repository",
        "app.data.repositories.expense_repository",
        "app.data.repositories.reporting_repository",
        "app.data.repositories.sync_repository",
        "app.domain.permissions",
        "app.domain.permissions.catalog",
        "app.domain.session",
        "app.domain.errors",
        "app.domain.services.auth_service",
        "app.domain.services.audit_service",
        "app.domain.services.category_service",
        "app.domain.services.customer_service",
        "app.domain.services.product_service",
        "app.domain.services.product_import",
        "app.domain.services.inventory_service",
        "app.domain.services.sale_service",
        "app.domain.services.receipt_service",
        "app.domain.services.exchange_service",
        "app.domain.services.supplier_service",
        "app.domain.services.purchase_service",
        "app.domain.services.expense_service",
        "app.domain.services.reporting_service",
        "app.domain.services.backup_service",
        "app.domain.services.sync_service",
        "app.domain.services.device_service",
        "app.barcode",
        "app.barcode.codes",
        "app.barcode.labels",
        "app.barcode.scanner",
        "app.printing",
        "app.printing.receipt",
        "app.printing.escpos",
        "app.printing.printer",
        "app.sync",
        "app.sync.cloud_models",
        "app.sync.cloud_db",
        "app.sync.cloud_api",
        "app.sync.schemas",
        "app.sync.client",
        "app.sync.apply",
        "app.sync.worker",
        "app.sync.device_registration",
        "app.security",
        "app.security.passwords",
        "app.utils",
        "app.utils.formatting",
        "app.ui",
        "app.ui.login",
        "app.ui.login.login_dialog",
        "app.ui.dashboard",
        "app.ui.dashboard.dashboard_page",
        "app.ui.pos",
        "app.ui.pos.pos_page",
        "app.ui.pos.popups",
        "app.ui.pos.quick_customer",
        "app.ui.products",
        "app.ui.products.products_page",
        "app.ui.products.product_form",
        "app.ui.customers",
        "app.ui.customers.customers_page",
        "app.ui.customers.customer_form",
        "app.ui.inventory",
        "app.ui.inventory.inventory_page",
        "app.ui.exchanges",
        "app.ui.exchanges.exchange_page",
        "app.ui.exchanges.exchange_dialog",
        "app.ui.exchanges.popups",
        "app.ui.purchases",
        "app.ui.purchases.purchases_page",
        "app.ui.purchases.purchase_form",
        "app.ui.suppliers",
        "app.ui.suppliers.suppliers_page",
        "app.ui.suppliers.supplier_form",
        "app.ui.expenses",
        "app.ui.expenses.expenses_page",
        "app.ui.expenses.expense_form",
        "app.ui.reports",
        "app.ui.reports.reports_page",
        "app.ui.reports.my_sales_page",
        "app.ui.settings",
        "app.ui.settings.settings_page",
        "app.ui.widgets",
        "app.ui.widgets.barcode_input",
        "app.ui.widgets.low_stock_popup",
        "app.ui.widgets.charts",
        "app.ui.theme",
        "PySide6.QtWidgets",
        "PySide6.QtCore",
        "PySide6.QtGui",
        "sqlalchemy.dialects.sqlite",
        "dotenv",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "tkinter",
        "matplotlib",
        "numpy",
        "pandas",
        "PIL",
        "scipy",
        "IPython",
        "jupyter",
        "notebook",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="FunmitePOS",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="FunmitePOS",
)
