"""Printing layer — receipts and labels."""

from __future__ import annotations

from app.printing.escpos import (  # noqa: F401
    DEFAULT_LOGO_PATH,
    LOGO_MAX_HEIGHT,
    LOGO_MAX_WIDTH,
    PRINTABLE_DOTS,
    ALIGN_CENTRE,
    ALIGN_LEFT,
    ALIGN_RIGHT,
    CODE_PAGE_PC437,
    CUT_PARTIAL,
    EMPHASIS_OFF,
    EMPHASIS_ON,
    INIT,
    EscPosRenderer,
    build_logo_command,
)
from app.printing.printer import (  # noqa: F401
    EscPosFilePrinter,
    InMemoryPrinter,
    NullPrinter,
    PrinterConfigStore,
    PrinterNotConfiguredError,
    PrinterState,
    PrinterUnavailableError,
    PrinterWriteFailureError,
    ReceiptPrintError,
    ReceiptPrinter,
    WindowsPrinter,
    create_printer,
    resolve_printer_name,
)
from app.printing.receipt import (  # noqa: F401
    PAYMENT_LABELS,
    PRINTABLE_WIDTH,
    RECEIPT_FOOTER,
    RECEIPT_GRAND_THANK,
    RECEIPT_PAYMENT_HEADER,
    RECEIPT_TAGLINE,
    RECEIPT_VISIT,
    SHOP_ADDRESS,
    SHOP_CATEGORY,
    SHOP_EMAIL,
    SHOP_NAME,
    SHOP_PHONE,
    SHOP_THANK_YOU,
    ReceiptBuilder,
    ReceiptData,
    ReceiptLine,
    discount_label,
    render_receipt_text,
)
