"""Product catalogue service (Phase 03).

Product records are Admin-managed per the permission matrix
(``CAP_CREATE_PRODUCT`` / ``CAP_EDIT_PRODUCT`` / ``CAP_CHANGE_PRICE``). Barcode
and product-code values are generated by the system when the Admin does not
supply one; the database ``UNIQUE`` constraints on ``products.barcode`` and
``products.product_code`` are the final guard against duplicates.

No product record is ever hard-deleted: products are deactivated via
``is_active`` so historical transactions keep their references.
"""

from __future__ import annotations

from decimal import Decimal

from sqlalchemy.orm import Session

from app.barcode.codes import NumericBarcodeGenerator
from app.data.models import (
    DEFAULT_MINIMUM_STOCK,
    Category,
    Product,
)
from app.data.repositories.product_repository import ProductRepository
from app.domain.errors import NotFoundError, ValidationError
from app.domain.permissions import (
    CAP_CHANGE_PRICE,
    CAP_CREATE_PRODUCT,
    CAP_EDIT_PRODUCT,
    CAP_SCAN_BARCODE,
    require_permission,
)
from app.domain.rules.validation import parse_decimal, parse_quantity
from app.domain.services.category_service import CategoryService
from app.domain.services.sync_service import SyncService

PRODUCT_CODE_PREFIX = "PRD"


class ProductService:
    """Use-case service for the product catalogue."""

    def __init__(self, session: Session, *, barcode_generator: NumericBarcodeGenerator | None = None) -> None:
        self.session = session
        self.products = ProductRepository(session)
        self.categories = CategoryService(session)
        self.barcodes = barcode_generator or NumericBarcodeGenerator(repository=self.products)

    def _sync(self) -> SyncService:
        return SyncService(self.session)

    # --- queries ---------------------------------------------------------- #

    def get(self, product_id: int) -> Product:
        product = self.products.get(product_id)
        if product is None:
            raise NotFoundError("Product not found.")
        return product

    def lookup_by_barcode(self, user, barcode: str) -> Product | None:
        """Barcode lookup for scanner input (shared by Admin and Cashier)."""
        require_permission(user, CAP_SCAN_BARCODE)
        value = (barcode or "").strip()
        if not value:
            return None
        return self.products.get_by_barcode(value)

    def search_products(
        self,
        user,
        query: str = "",
        *,
        category_id: int | None = None,
        include_inactive: bool = False,
        limit: int = 50,
    ) -> list[Product]:
        """Fast catalogue search across name, code and barcode (shared)."""
        require_permission(user, CAP_SCAN_BARCODE)
        return self.products.search(
            query,
            category_id=category_id,
            include_inactive=include_inactive,
            limit=limit,
        )

    # --- catalogue management (Admin) ------------------------------------ #

    def create(
        self,
        user,
        *,
        name: str,
        category: str | Category,
        cost_price,
        selling_price,
        quantity=0,
        minimum_stock: int | None = None,
        product_code: str | None = None,
        barcode: str | None = None,
        brand: str | None = None,
        size: str | None = None,
        color: str | None = None,
        image_path: str | None = None,
    ) -> Product:
        """Create a product, generating a unique barcode and product code if absent."""
        require_permission(user, CAP_CREATE_PRODUCT)

        name = (name or "").strip()
        if not name:
            raise ValidationError("Product name is required.")
        cost = parse_decimal(cost_price, "cost price")
        selling = parse_decimal(selling_price, "selling price")
        quantity = parse_quantity(quantity, "quantity", minimum=0)
        minimum = (
            DEFAULT_MINIMUM_STOCK
            if minimum_stock is None
            else parse_quantity(minimum_stock, "minimum stock", minimum=0)
        )

        category_record = self._resolve_category(user, category)

        code = (product_code or "").strip() or self._next_product_code()
        if self.products.get_by_product_code(code) is not None:
            raise ValidationError(f"Product code '{code}' already exists.")

        value = (barcode or "").strip() or self.barcodes.generate(self.session)
        if self.products.get_by_barcode(value) is not None:
            raise ValidationError(f"Barcode '{value}' already exists.")

        product = Product(
            product_code=code,
            name=name,
            category_id=category_record.id,
            brand=brand.strip() if brand else None,
            size=size.strip() if size else None,
            color=color.strip() if color else None,
            cost_price=cost,
            selling_price=selling,
            quantity=quantity,
            minimum_stock=minimum,
            barcode=value,
            image_path=image_path.strip() if image_path else None,
            is_active=True,
        )
        self.products.add(product)
        self.session.flush()
        self._sync().enqueue_create("product", product.id, {
            "sync_uuid": product.sync_uuid,
            "product_code": product.product_code,
            "name": product.name,
            "category_id": product.category_id,
            "brand": product.brand,
            "size": product.size,
            "color": product.color,
            "cost_price": str(product.cost_price),
            "selling_price": str(product.selling_price),
            "quantity": product.quantity,
            "minimum_stock": product.minimum_stock,
            "barcode": product.barcode,
            "is_active": product.is_active,
            "version": product.version,
        })
        return product

    def update(
        self,
        user,
        product_id: int,
        *,
        name: str | None = None,
        category: str | Category | None = None,
        brand: str | None = None,
        size: str | None = None,
        color: str | None = None,
        cost_price=None,
        selling_price=None,
        quantity=None,
        minimum_stock: int | None = None,
        product_code: str | None = None,
        barcode: str | None = None,
        image_path: str | None = None,
        is_active: bool | None = None,
    ) -> Product:
        """Update an existing product. Price changes also need ``CAP_CHANGE_PRICE``."""
        require_permission(user, CAP_EDIT_PRODUCT)
        if cost_price is not None or selling_price is not None:
            require_permission(user, CAP_CHANGE_PRICE)

        product = self.get(product_id)

        if name is not None:
            cleaned = (name or "").strip()
            if not cleaned:
                raise ValidationError("Product name is required.")
            product.name = cleaned
        if category is not None:
            product.category_id = self._resolve_category(user, category).id
        if brand is not None:
            product.brand = brand.strip() if brand else None
        if size is not None:
            product.size = size.strip() if size else None
        if color is not None:
            product.color = color.strip() if color else None
        if cost_price is not None:
            product.cost_price = parse_decimal(cost_price, "cost price")
        if selling_price is not None:
            product.selling_price = parse_decimal(selling_price, "selling price")
        if quantity is not None:
            product.quantity = parse_quantity(quantity, "quantity", minimum=0)
        if minimum_stock is not None:
            product.minimum_stock = parse_quantity(minimum_stock, "minimum stock", minimum=0)
        if product_code is not None:
            cleaned = product_code.strip()
            if not cleaned:
                raise ValidationError("Product code cannot be empty.")
            clash = self.products.get_by_product_code(cleaned)
            if clash is not None and clash.id != product.id:
                raise ValidationError(f"Product code '{cleaned}' already exists.")
            product.product_code = cleaned
        if barcode is not None:
            cleaned = barcode.strip()
            if not cleaned:
                raise ValidationError("Barcode cannot be empty.")
            clash = self.products.get_by_barcode(cleaned)
            if clash is not None and clash.id != product.id:
                raise ValidationError(f"Barcode '{cleaned}' already exists.")
            product.barcode = cleaned
        if image_path is not None:
            product.image_path = image_path.strip() if image_path else None
        if is_active is not None:
            product.is_active = bool(is_active)
        self.session.flush()
        self._sync().enqueue_update("product", product.id, {
            "sync_uuid": product.sync_uuid,
            "product_code": product.product_code,
            "name": product.name,
            "category_id": product.category_id,
            "brand": product.brand,
            "size": product.size,
            "color": product.color,
            "cost_price": str(product.cost_price),
            "selling_price": str(product.selling_price),
            "quantity": product.quantity,
            "minimum_stock": product.minimum_stock,
            "barcode": product.barcode,
            "is_active": product.is_active,
            "version": product.version,
        })
        return product

    def deactivate(self, user, product_id: int) -> Product:
        """Soft-delete a product: deactivate it, never remove the record."""
        require_permission(user, CAP_EDIT_PRODUCT)
        product = self.get(product_id)
        product.is_active = False
        return product

    def activate(self, user, product_id: int) -> Product:
        require_permission(user, CAP_EDIT_PRODUCT)
        product = self.get(product_id)
        product.is_active = True
        return product

    # --- helpers ---------------------------------------------------------- #

    def _resolve_category(self, user, category: str | Category) -> Category:
        if isinstance(category, Category):
            return category
        return self.categories.get_or_create(user, category)

    def _next_product_code(self) -> str:
        current = self.products.max_code_number(PRODUCT_CODE_PREFIX)
        return f"{PRODUCT_CODE_PREFIX}-{current + 1:06d}"
